<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:asanservice" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:asanservice">
<types>
<xsd:schema targetNamespace="urn:asanservice"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="progressSessionRequest">
  <part name="parameters" type="xsd:string" /></message>
<message name="progressSessionResponse">
  <part name="parameters" type="xsd:string" /></message>
<portType name="asanservicePortType">
  <operation name="progressSession">
    <documentation>Get a listing of products by category</documentation>
    <input message="tns:progressSessionRequest"/>
    <output message="tns:progressSessionResponse"/>
  </operation>
</portType>
<binding name="asanserviceBinding" type="tns:asanservicePortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="progressSession">
    <soap:operation soapAction="urn:asanservice#progressSession" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:asanservice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:asanservice" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="asanservice">
  <port name="asanservicePort" binding="tns:asanserviceBinding">
    <soap:address location="http://69.16.245.83/service.php"/>
  </port>
</service>
</definitions>